import { UserTable } from './modules/users/user.table';
import { SignInMethodTable } from './modules/users/sign-in-method/sign-in-method.table';
import { PasswordSignInMethodTable } from './modules/users/sign-in-method/password-sign-in-method.table';
import { PartnerTable } from './modules/partner/partner.table';
import { DeliveryMethodTable } from './modules/partner/delivery-method/delivery-method.table';
import { BusinessTypeTable } from './modules/partner/business-type/business-type.table';
import { CatalogTable } from './modules/partner/catalog/catalog.table';
import { CatalogCategoryTable } from './modules/partner/catalog/catalog-category.table';
import { CatalogItemTable } from './modules/partner/catalog/catalog-item.table';
import { PartnerHourTable } from './modules/partner/partner-hour.table';
import { UserRoleTable } from './modules/users/user-role/user-role.table';
import { RoleTable } from './modules/role/role.table';
import { VehicleTypeTable } from './modules/employees/vehicle-types/vehicle-type.table';
import { EmployeeTable } from './modules/employees/employee.table';
import { SchedulePreferenceTable } from './modules/employees/schedule-preference/schedule-preference.table';
import { HourPreferenceTable } from './modules/employees/hours-preference/hours-preference.table';
import { EmployeeDocumentationTable } from './modules/employees/employee-documentation/employee-documentation.table';
import { ChatTable, UserChatTable, MessageTable, PushTokenTable } from './modules/chat/chat.table';
import { DeliveryTrackingTable } from './modules/delivery-tracking/delivery-tracking.table';
import { OrderItemTable, OrderTable } from './modules/orders/order.table';
import { CustomerTable } from './modules/customer/customer.table';
import { PaymentTable } from './modules/payment/payment.table';
import { CourierScheduleTable, TimeEntryTable } from './modules/employees/courier-schedule/schedule.table';
import { CountryTable, CityTable, PostalCodeTable, StreetTable, AddressTable } from './modules/address/address.tables';
import { RefreshTokenTable, PasswordResetTokenTable } from './modules/authentication';
import { DeliveryTable, CourierAvailabilityTable, CourierLocationTable } from './modules/delivery/delivery.table';

export interface Database {
    refresh_token: RefreshTokenTable;
    user: UserTable;
    sign_in_method: SignInMethodTable;
    password_sign_in_method: PasswordSignInMethodTable;
    password_reset_token: PasswordResetTokenTable;
    partner: PartnerTable;
    delivery_method: DeliveryMethodTable;
    business_type: BusinessTypeTable;
    catalog: CatalogTable;
    catalog_category: CatalogCategoryTable;
    catalog_item: CatalogItemTable;
    partner_hour: PartnerHourTable;
    address: AddressTable;
    street: StreetTable;
    country: CountryTable;
    city: CityTable;
    postal_code: PostalCodeTable;
    user_role: UserRoleTable;
    role: RoleTable;
    vehicle_type: VehicleTypeTable;
    employee: EmployeeTable;
    schedule_preference: SchedulePreferenceTable;
    hour_preference: HourPreferenceTable;
    employee_documentation: EmployeeDocumentationTable;
    chat: ChatTable;
    user_chat: UserChatTable;
    message: MessageTable;
    push_token: PushTokenTable;
    delivery_tracking: DeliveryTrackingTable;
    order: OrderTable;
    order_item: OrderItemTable;
    customer: CustomerTable;
    payment: PaymentTable;
    courier_schedule: CourierScheduleTable;
    time_entry: TimeEntryTable;
    delivery: DeliveryTable;
    courier_availability: CourierAvailabilityTable;
    courier_location: CourierLocationTable;
}
