name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Write JWT keys
      run: |
        mkdir -p keys
        echo "${{ secrets.PRIVATE_KEY_PEM }}" > keys/private.pem
        echo "${{ secrets.PUBLIC_KEY_PEM }}" > keys/public.pem

    - name: Build and start services for testing
      run: docker compose up -d --build

    - name: Wait for Postgres to be ready
      run: |
        until docker exec $(docker compose ps -q postgres) pg_isready -U postgres; do
          sleep 1
        done

    - name: Run tests
      run: docker compose exec -T app npm test

    - name: Show app logs if tests fail
      if: failure()
      run: docker compose logs app

    - name: Stop services
      run: docker compose down

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: rokdev01/mmr-delivery-api:latest

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag my-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
            ssh -p 49542 -o StrictHostKeyChecking=no deploy@135.125.235.169 << 'EOF'
            # Login to Docker Hub (recommended approach for private images)
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u rokdev01 --password-stdin
            # Pull the image from Docker Hub
            docker pull rokdev01/mmr-delivery-api:latest
            # Stop and remove existing container
            docker stop my-container || true
            docker rm my-container || true
            # Run new container with the pulled image
            docker run -d --name my-container -p 80:3000 rokdev01/mmr-delivery-api:latest
            EOF
